### ISSUE TITLE
Use "orderBy" to traverse a collection's documents

### ISSUE THREAD

**Issue by ojm-it** [kafkas/firecode#22]
Hello,
Is it possible to use "orderBy" to traverse a collection in a certain order ?

Suppose I have a collection "Data" with these kinds of docs : 
```
{
  id : ....,
  name : ....,
}
```
I would like to traverse this collection in a way that the docs are ordered by `id` (or by `name`) between the different batches. What I mean by that is that the docs of batch1 should all have a "lower" id/name than the docs in batch 2, and so forth. The docs don't have to be ordered inside the same batch. 

Is that possible? In what order is the collection traversed by default?

Thanks.

**Comment by kafkas** [comment]
@ojm-it Yes, this is possible because [firestore.Query](https://googleapis.dev/nodejs/firestore/latest/Query.html) is a valid [Traversable](https://kafkas.github.io/firecode/0.8.2/modules.html#traversable). So you can just do

```ts
const query = firestore().collection('Data').orderBy('name', 'asc');
const traverser = createTraverser(query);
```

The docs will be ordered between batches as well as within the same batch. The default order is by document id which is the same as the order in which you receive the docs with `collectionRef.get()` (i.e. how they appear on Firebase console).

**Comment by ojm-it** [comment]
Thank you very much ! Keep up the good work 😀
